language: node_js
node_js:
  - "node"
warnings_are_errors: false
install:
  - npm install && npm run build
script:
  - echo "deploy"
deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_TOKEN