language: node_js
node_js: 
  - "12.18"
script:
  - echo "Deploying"
install:
  - npm install -g firebase-tools
  - npm install -g react-scripts
  - react-scripts build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN